DROP TABLE IF EXISTS passes CASCADE;

CREATE TABLE passes (
  id VARCHAR(255) PRIMARY KEY,
  season VARCHAR(255) NOT NULL REFERENCES seasons(id) ON DELETE CASCADE,
  release_date DATE NOT NULL,
  price INT NOT NULL
);