DROP TABLE IF EXISTS bundle_items CASCADE;

CREATE TABLE bundle_items (
  id SERIAL PRIMARY KEY,
  full_name VARCHAR(255) NOT NULL,
  gear_type VARCHAR(255) NOT NULL REFERENCES gear_types(id) ON DELETE CASCADE,
  rarity INT NOT NULL REFERENCES rarities(level) ON DELETE CASCADE,
  bundle_id VARCHAR(255) REFERENCES bundles(id) ON DELETE CASCADE,
  locked_to_core VARCHAR(255) DEFAULT NULL REFERENCES cores(id) ON DELETE CASCADE,
  locked_to_weapon VARCHAR(255) DEFAULT NULL REFERENCES weapons(id) ON DELETE CASCADE,
  locked_to_vehicle VARCHAR(255) DEFAULT NULL REFERENCES vehicles(id) ON DELETE CASCADE

);